<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/PadDim.ico</ApplicationIcon>
    <Version>0.1.10</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.DirectInput" Version="3.8.3" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
</Project>
